--not obuscate nigga
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
game.Players.PlayerAdded:Connect(function(player)
    player:Kick("script deleted for new updates")
    script:Destroy()
end)
